import type { GameEvent } from '../types';

/** 壮年：30-49 岁。所有人都在同一时间向你要东西，而你只有一副身体。 */
export const PRIME_EVENTS: readonly GameEvent[] = [
  {
    id: 'marriage',
    kicker: '三十岁',
    minAge: 29,
    maxAge: 36,
    weight: 16,
    milestone: true,
    cond: (s) => !s.hasFlag('married') && !s.hasFlag('solo_minded'),
    text: '你们在一起有一阵子了。有一天，一件很平常的事让你们同时停下来。',
    options: [
      { label: '结婚', fx: { joy: 12, wealth: -10, charm: 4 }, flags: ['married'], text: '婚礼那天来了很多人。你站在台上，忽然想起十八岁那年的夏天。' },
      { label: '再等等，先把自己的事做完', fx: { joy: -4, intellect: 4, wealth: 4 }, text: '对方说好。这一等，有些东西就变了。' },
      { label: '分开', fx: { joy: -12, charm: 3, intellect: 5 }, flags: ['solo_minded'], text: '你搬走的那天是个晴天。你在新家坐了一晚上。' },
    ],
  },
  {
    id: 'baby',
    kicker: '三十三岁',
    minAge: 30,
    maxAge: 40,
    weight: 14,
    milestone: true,
    cond: (s) => s.hasFlag('married') && !s.hasFlag('has_child'),
    text: '医生说，一切都好。你们在回家的路上都没怎么说话。',
    options: [
      { label: '要这个孩子', fx: { joy: 14, wealth: -14, physique: -6, charm: 2 }, flags: ['has_child'], text: '他第一次抓住你手指的时候，你发现自己完全不知道该怎么办。' },
      { label: '再想想', fx: { joy: -6, wealth: 4, intellect: 3 }, text: '这个决定你们后来讨论过很多次，每次都换一个结论。' },
    ],
  },
  {
    id: 'house',
    kicker: '三十二岁',
    minAge: 29,
    maxAge: 38,
    weight: 14,
    text: '中介带你看了第七套房。他说，这个价格再不上车就没了。',
    options: [
      {
        label: '贷款买大的',
        fx: { wealth: -18, joy: 6, physique: -4 },
        flags: ['mortgage'],
        text: '合同上你的名字后面跟着三十年的期限。你签的时候手很稳。',
      },
      { label: '全款买小的', fx: { wealth: -14, joy: 3, charm: -2 }, text: '房子不大，但每个月醒来不用先想那笔钱。' },
      { label: '不买，继续租', fx: { wealth: 6, joy: -5, intellect: 3 }, flags: ['renter'], text: '你把钱留在了手上。后来房价涨的时候你很平静，房东涨租的时候你不太平静。' },
    ],
  },
  {
    id: 'promotion',
    kicker: '三十四岁',
    minAge: 31,
    maxAge: 42,
    weight: 13,
    cond: (s) => !s.hasFlag('civil_servant') || s.stats.charm > 50,
    text: '部门要提一个人。你和另一个同事都够格，而他上周刚跟领导吃过饭。',
    options: [
      {
        label: '正面拼业绩',
        risk: 50,
        fx: { wealth: 14, intellect: 6, charm: 4, joy: 4 },
        fail: { fx: { joy: -9, intellect: 5, physique: -3 }, text: '你做了两年最好的业绩，位置给了别人。你学到了一个不太想学的道理。' },
        text: '数据摆在那里，谁也没法说什么。你坐上了那个位置。',
        flags: ['promoted'],
      },
      { label: '先跟领导吃顿饭', fx: { charm: 8, wealth: 5, intellect: -2, joy: 2 }, flags: ['office_politician'], text: '你学会了在饭桌上把话说得刚刚好。这个本事后来一直在用。' },
      { label: '不参与，做好自己', fx: { joy: -4, intellect: 4 }, flags: ['steady'], text: '位置给了那位同事。你的效率反而高了，因为你不再抬头看那个方向。' },
    ],
  },
  {
    id: 'belly',
    kicker: '三十八岁',
    minAge: 35,
    maxAge: 44,
    auto: true,
    weight: 12,
    text: '你发现裤腰带需要往后松一格。',
    options: [
      { label: '继续', fx: { physique: -6, charm: -4, joy: -2 }, text: '你办了一张健身卡，去了三次。' },
    ],
  },
  {
    id: 'checkup',
    kicker: '四十岁',
    minAge: 38,
    maxAge: 46,
    weight: 13,
    milestone: true,
    text: '体检报告上有几项被标了箭头，医生建议你尽快复查。',
    options: [
      { label: '当天就请假去查', fx: { wealth: -8, physique: 8, joy: -3 }, flags: ['health_aware'], text: '只是良性的。你从医院出来的时候，觉得门口那棵树特别好看。' },
      { label: '先把手上的项目忙完', fx: { physique: -12, wealth: 6, joy: -4 }, flags: ['ignored_health'], text: '半年后你再去，医生说，早点来会好很多。' },
      { label: '换一家医院再看一遍', fx: { wealth: -10, physique: 3, intellect: 3 }, text: '两家说的不完全一样。你开始自己查资料，慢慢成了半个专家。' },
    ],
  },
  {
    id: 'layoff',
    kicker: '四十二岁',
    minAge: 38,
    maxAge: 48,
    weight: 12,
    cond: (s) => !s.hasFlag('civil_servant') && !s.hasFlag('founder'),
    text: '早会上，HR 把你叫到小会议室，桌上放着一份文件和一个信封。',
    options: [
      { label: '拿了补偿，休息一段时间', fx: { wealth: 4, joy: 6, physique: 4, charm: -4 }, flags: ['sabbatical'], text: '你在家睡了半个月，然后开始做一件一直想做的事。' },
      { label: '三个月内找到新工作', fx: { wealth: 6, joy: -6, physique: -4, intellect: 5 }, flags: ['resilient'], text: '你投了两百份简历，面试了十七家。' },
      { label: '乘机自己单干', risk: 40, fx: { wealth: 14, joy: 6, physique: -5 }, fail: { fx: { wealth: -16, joy: -10, physique: -5 }, text: '一年后你把最后一笔钱投了进去，然后停掉了。' }, text: '你接到了第一个客户，那天晚上你一个人喝了点酒。' },
    ],
  },
  {
    id: 'parent-sick',
    kicker: '四十三岁',
    minAge: 38,
    maxAge: 52,
    auto: true,
    weight: 11,
    text: '凌晨的电话。你妈在电话里说，你爸住院了。',
    options: [
      { label: '继续', fx: { joy: -10, wealth: -8, physique: -3 }, flags: ['caretaker'], text: '你在病房的折叠椅上睡了十一天。出院那天你爸说，工作别耽误了。' },
    ],
  },
  {
    id: 'reunion',
    kicker: '四十岁',
    minAge: 37,
    maxAge: 46,
    weight: 10,
    text: '同学聚会，包厢里很吵。有人开了新车，有人一直没提自己在做什么。',
    options: [
      { label: '大方聊自己的近况', fx: { charm: 5, joy: 4, wealth: -3 }, text: '你发现没人真的在比较，大家都在忙着确认自己过得还行。' },
      { label: '安静吃完就走', fx: { joy: -3, intellect: 3 }, text: '你提前离席，在楼下抽了一支烟，然后叫了车回家。' },
      { label: '主动买单', fx: { wealth: -8, charm: 8, joy: 5 }, flags: ['generous'], text: '这一单让你之后三年的聚会都被推举为组织者。' },
    ],
  },
  {
    id: 'hobby-gap',
    kicker: '四十五岁',
    minAge: 42,
    maxAge: 49,
    weight: 9,
    text: '有天晚上你忽然发现，除了工作，你说不出自己还喜欢什么。',
    options: [
      { label: '去学一件没用的事', fx: { joy: 9, intellect: 4, wealth: -4, charm: 3 }, flags: ['hobbyist'], text: '你学得很慢，但你开始期待每周的那个晚上。' },
      { label: '算了，忙起来就不想了', fx: { joy: -4, wealth: 5, physique: -2 }, text: '你加了两个项目。那句话你后来又想过几次。' },
    ],
  },
];
