import type { GameEvent } from '../types';

/** 少年：7-17 岁。被安排的人生里，人只能在缝隙里偷偷长出自己的形状。 */
export const TEEN_EVENTS: readonly GameEvent[] = [
  {
    id: 'math-camp',
    kicker: '九岁',
    minAge: 8,
    maxAge: 10,
    weight: 12,
    text: '你妈把你塞进了周末的奥数班。第一节课讲的是鸡兔同笼。',
    options: [
      { label: '认真听，回家还刷题', fx: { intellect: 9, joy: -5 }, flags: ['grinder'], text: '你成了班里唯一能跟上的人，代价是再也没有周末。' },
      { label: '逃课去操场打球', fx: { physique: 7, intellect: -2, joy: 5 }, flags: ['playful'], text: '太阳很好，球落在地上弹起的声音，你记了一辈子。' },
      { label: '趴在桌上睡觉', fx: { joy: 3, intellect: 1, charm: -2 }, text: '老师给你妈打了电话。你回家挨了一顿。' },
    ],
  },
  {
    id: 'parents-fight',
    kicker: '十岁',
    minAge: 8,
    maxAge: 13,
    auto: true,
    weight: 9,
    text: '半夜你醒了，客厅有压低的声音在吵。',
    options: [
      { label: '继续', fx: { joy: -6, intellect: 3 }, flags: ['sensitive'], text: '你躺着没动，听完了全部。第二天早上他们装作什么都没发生，你也装作什么都没听见。' },
    ],
  },
  {
    id: 'pocket-money',
    kicker: '十岁',
    minAge: 9,
    maxAge: 12,
    weight: 10,
    text: '你攒了三个月的零花钱，一共一百二十块。',
    options: [
      { label: '存起来', fx: { wealth: 6, joy: -3 }, flags: ['thrifty'], text: '你把钱夹在一本从来不看的书里，每隔几天就去摸一下。' },
      { label: '买零食，和同学分着吃', fx: { joy: 6, charm: 4, wealth: -2 }, text: '那个下午你成了全班最受欢迎的人。' },
      { label: '买一张想要很久的游戏卡', fx: { joy: 8, wealth: -4, intellect: 1 }, text: '你玩了整整一个暑假，通关那天有点失落。' },
    ],
  },
  {
    id: 'copy-homework',
    kicker: '十二岁',
    minAge: 11,
    maxAge: 14,
    weight: 13,
    text: '同桌把作业本推过来一半，小声说：就抄一道。',
    options: [
      { label: '借他抄', fx: { charm: 5, intellect: -2, joy: 2 }, flags: ['loyal'], text: '他后来在你最需要的时候帮过你一次。' },
      { label: '拒绝', fx: { intellect: 3, charm: -4 }, flags: ['principled'], text: '他一个月没跟你说话。你少了抄作业的能力，也少了被拖下水的能力。' },
      { label: '收他五毛钱', fx: { wealth: 5, charm: -2, intellect: 2 }, flags: ['hustler'], text: '期末你赚了十一块。这是你人生第一笔生意。' },
    ],
  },
  {
    id: 'novel-addict',
    kicker: '十三岁',
    minAge: 12,
    maxAge: 15,
    weight: 11,
    text: '你在一本旧书里读到一个完全不同的世界，然后开始在上课时间读它。',
    options: [
      { label: '看，看得昏天黑地', fx: { intellect: 6, joy: 7, physique: -4 }, flags: ['dreamer'], text: '一个月你读了十七本，视力掉了两百度。' },
      { label: '只看一点，控制住自己', fx: { intellect: 4, joy: 3 }, text: '你学会了给自己划界，划得不太好看，但管用。' },
    ],
  },
  {
    id: 'sports-day',
    kicker: '十三岁',
    minAge: 12,
    maxAge: 15,
    weight: 10,
    text: '运动会八百米，你是被临时凑上去的那个人。',
    options: [
      {
        label: '咬牙跑完',
        risk: 55,
        hint: '体质越好越可能撑住',
        fx: { physique: 6, joy: 4, charm: 4 },
        fail: { fx: { physique: -3, joy: -4, charm: 2 }, text: '最后一百米你吐在了跑道上，但全班都在喊你的名字。' },
        text: '你冲过终点线，腿抖得站不住，有人扶住了你。',
      },
      { label: '跑到一半装肚子疼', fx: { joy: -2, physique: -1 }, text: '没人拆穿你，你自己知道。' },
    ],
  },
  {
    id: 'internet-cafe',
    kicker: '十五岁',
    minAge: 14,
    maxAge: 17,
    weight: 11,
    text: '同学说网吧新开了个机器很好的区，五块钱一小时。',
    options: [
      {
        label: '翻墙出来通宵',
        risk: 45,
        fx: { joy: 9, physique: -6, intellect: 2 },
        fail: { fx: { joy: -8, physique: -5, charm: -2 }, text: '你爸在网吧门口等到了凌晨三点。他没打你，一路没说话。' },
        text: '天亮时你们从后门溜出去，看见街上扫地的环卫工，觉得自己很自由。',
      },
      { label: '不去，回家做题', fx: { intellect: 5, joy: -4 }, flags: ['grinder'], text: '你在窗边看他们走远，把卷子摊开，心里有点空。' },
    ],
  },
  {
    id: 'teacher-call',
    kicker: '十三岁',
    minAge: 11,
    maxAge: 16,
    auto: true,
    weight: 8,
    text: '你被叫去办公室，班主任当着别的老师的面念了你的成绩单。',
    options: [
      { label: '继续', fx: { joy: -5, intellect: 3 }, flags: ['thorny'], text: '你第一次意识到，有些人说话不是为了帮你。' },
    ],
  },
  {
    id: 'bully-witness',
    kicker: '十四岁',
    minAge: 13,
    maxAge: 16,
    weight: 9,
    text: '走廊尽头，几个人围着一个不太说话的男生，笑声很响。',
    options: [
      { label: '走过去站在他旁边', fx: { charm: 6, physique: -2, joy: 4 }, flags: ['just'], text: '什么都没发生。但你和他从此成了一辈子的朋友。' },
      { label: '快步走开', fx: { joy: -5, intellect: 2 }, text: '你走得很快。这件事你后来想起过很多次。' },
      { label: '跟着笑', fx: { charm: 3, joy: -8 }, flags: ['coward'], text: '笑声里有你。你回家路上一直不太舒服。' },
    ],
  },
  {
    id: 'crush',
    kicker: '十五岁',
    minAge: 14,
    maxAge: 17,
    weight: 12,
    text: '你发现自己会在课间不自觉地去走廊的那一头。',
    options: [
      { label: '写一封信，塞给他/她', fx: { charm: 5, joy: 7 }, flags: ['brave_heart'], text: '信被回了。你们一起走了三个月的放学路。' },
      { label: '一直放在心里', fx: { joy: -3, intellect: 4 }, flags: ['quiet_heart'], text: '很多年后你才听说，他/她当时也在等。' },
      { label: '告诉全世界', fx: { charm: 3, joy: -2, intellect: -2 }, text: '全班都知道了。他/她一周没跟你说话。' },
    ],
  },
  {
    id: 'family-move',
    kicker: '十六岁',
    minAge: 15,
    maxAge: 17,
    weight: 7,
    cond: (s) => s.hasFlag('merchant') || s.stats.wealth > 55,
    text: '父母决定搬家，你要换一所学校，还有一个学期就高考。',
    options: [
      { label: '跟着走', fx: { joy: -6, charm: -3, intellect: 4 }, text: '新学校的人已经有了各自的小圈子。你花了很久才挤进去。' },
      { label: '留下来，自己住', fx: { joy: -4, physique: -3, intellect: 5 }, flags: ['independent'], text: '你第一次一个人吃完了一整个月的饭。' },
    ],
  },
];
