import type { GameEvent } from '../types';

/** 青年：18-29 岁。所有重要的事都在这一段挤着发生。 */
export const YOUTH_EVENTS: readonly GameEvent[] = [
  {
    id: 'gaokao-top',
    kicker: '十八岁',
    minAge: 18,
    maxAge: 18,
    weight: 100,
    milestone: true,
    cond: (s) => s.stats.intellect >= 62,
    text: '高考放榜。你的名字出现在那张贴在墙上的红纸最上面几行。',
    options: [
      { label: '名校热门专业', fx: { intellect: 8, wealth: 6, joy: -3 }, flags: ['elite'], text: '你选了父母都懂的那个专业。四年后你才发现自己不喜欢它。' },
      { label: '名校冷门专业', fx: { intellect: 12, joy: 4, wealth: -2 }, flags: ['elite', 'scholar'], text: '别人问你学什么，你要解释三句。但你在图书馆里过得非常好。' },
      { label: '出国', fx: { intellect: 9, charm: 6, wealth: -14, joy: 3 }, flags: ['elite', 'abroad'], text: '你在机场回头看了一眼。这一走是七年。' },
    ],
  },
  {
    id: 'gaokao-mid',
    kicker: '十八岁',
    minAge: 18,
    maxAge: 18,
    weight: 100,
    milestone: true,
    cond: (s) => s.stats.intellect >= 38 && s.stats.intellect < 62,
    text: '高考放榜。分数不上不下，够得着很多门，但没有一扇门是为你开的。',
    options: [
      { label: '上一所普通本科', fx: { intellect: 5, joy: 2 }, flags: ['normal_college'], text: '四年过得很快，你记住的都是一些没用的事。' },
      { label: '复读一年', fx: { intellect: 10, joy: -8, physique: -3 }, flags: ['repeater'], text: '第二次进考场的时候，你的手很稳。' },
      { label: '不读了，出去打工', fx: { wealth: 6, physique: 5, intellect: -3, joy: 1 }, flags: ['early_worker'], text: '你十九岁开始给家里寄钱。' },
    ],
  },
  {
    id: 'gaokao-low',
    kicker: '十八岁',
    minAge: 18,
    maxAge: 18,
    weight: 100,
    milestone: true,
    cond: (s) => s.stats.intellect < 38,
    text: '高考放榜。你在那张纸上找了很久，才在最下面找到自己。',
    options: [
      { label: '去读专科，学门手艺', fx: { intellect: 4, physique: 4, wealth: 4 }, flags: ['craftsman'], text: '你学的是一门手上功夫，后来它养了你半辈子。' },
      { label: '复读，赌一把', fx: { intellect: 8, joy: -9, physique: -4 }, flags: ['repeater'], text: '第二次也没考好。但你不再怕考试了。' },
      { label: '直接进社会', fx: { wealth: 5, charm: 5, physique: 3, intellect: -2 }, flags: ['early_worker'], text: '你比同龄人早四年学会了怎么跟人打交道。' },
    ],
  },
  {
    id: 'club',
    kicker: '二十岁',
    minAge: 19,
    maxAge: 21,
    weight: 12,
    text: '开学社团招新，一条街都是桌子。',
    options: [
      { label: '进学生会', fx: { charm: 7, intellect: 2, joy: -2 }, flags: ['socialite'], text: '你学会了排座位、写通知，还有在饭桌上敬酒。' },
      { label: '进辩论队', fx: { intellect: 8, charm: 4, joy: 2 }, flags: ['debater'], text: '你说话开始有人听了。' },
      { label: '什么都不进，去图书馆', fx: { intellect: 9, charm: -3, joy: 1 }, flags: ['loner'], text: '四年里你借的书比认识的人多。' },
    ],
  },
  {
    id: 'intern',
    kicker: '二十一岁',
    minAge: 20,
    maxAge: 23,
    weight: 12,
    cond: (s) => !s.hasFlag('early_worker'),
    text: '第一份实习，工资一天八十，通勤单程一小时四十分钟。',
    options: [
      { label: '做满，把活干到最好', fx: { intellect: 6, physique: -3, wealth: 3, charm: 3 }, flags: ['diligent'], text: '带你的那个人走的时候推荐了你。' },
      { label: '混过去，主要为了盖章', fx: { joy: 3, intellect: -1 }, text: '你盖到了章，也知道了混日子是什么手感。' },
    ],
  },
  {
    id: 'confess',
    kicker: '二十二岁',
    minAge: 20,
    maxAge: 26,
    weight: 12,
    text: '你和一个常常一起吃饭的人，走到了一段谁都不说破的距离。',
    options: [
      {
        label: '说破它',
        risk: 60,
        fx: { charm: 4, joy: 10 },
        fail: { fx: { joy: -8, charm: 2 }, text: '对方沉默了几秒，说了句「我们还是朋友吧」。你们后来真的还是朋友。' },
        text: '对方愣了一下，然后笑了。你们在一起了。',
        flags: ['loved'],
      },
      { label: '继续当朋友', fx: { joy: -4, charm: 3 }, flags: ['what_if'], text: '你们做了很多年的朋友，偶尔在深夜想一下如果。' },
    ],
  },
  {
    id: 'job-hunt',
    kicker: '二十三岁',
    minAge: 22,
    maxAge: 25,
    weight: 14,
    cond: (s) => !s.hasFlag('early_worker'),
    text: '毕业。你面前摆着几条路，每一条都在劝你放弃别的什么。',
    options: [
      { label: '去大厂，拿高薪', fx: { wealth: 16, intellect: 5, physique: -6, joy: -4 }, flags: ['bigtech'], text: '工资到账那天你请全宿舍吃了饭。三个月后你开始失眠。' },
      { label: '考公上岸', fx: { wealth: 6, joy: 4, intellect: 3, charm: -2 }, flags: ['civil_servant'], text: '你爸妈在小区里跟人说了半个月。' },
      { label: '进一家小公司', fx: { wealth: 8, charm: 6, intellect: 4, joy: 2 }, flags: ['smallco'], text: '一个人干三个人的活，也长了三种本事。' },
      { label: '先不工作，四处走走', fx: { joy: 12, wealth: -10, charm: 5, physique: 3 }, flags: ['wanderer'], text: '你用一个夏天把攒的钱花光了，换回来一些没法写进简历的东西。' },
    ],
  },
  {
    id: 'first-salary',
    kicker: '二十四岁',
    minAge: 23,
    maxAge: 27,
    auto: true,
    weight: 10,
    text: '第一个月工资到账。',
    options: [
      { label: '继续', fx: { joy: 5, wealth: 3 }, text: '你盯着短信看了很久。那串数字比你以为的少，但它是你自己的。' },
    ],
  },
  {
    id: 'weird-roommate',
    kicker: '二十四岁',
    minAge: 22,
    maxAge: 27,
    weight: 11,
    text: '合租的室友从来不洗碗，但会在凌晨两点煮泡面。',
    options: [
      { label: '当面说清楚', fx: { charm: 5, joy: 3, intellect: 2 }, flags: ['direct'], text: '你们吵了一架，然后成了还不错的朋友。' },
      { label: '忍到自己搬走', fx: { joy: -5, wealth: -4, physique: -2 }, text: '你搬的时候他没出来送你。' },
    ],
  },
  {
    id: 'startup-invite',
    kicker: '二十六岁',
    minAge: 24,
    maxAge: 29,
    weight: 10,
    cond: (s) => s.stats.intellect > 45 || s.hasFlag('hustler'),
    text: '朋友拉着你说，一起做吧，稳赚不赔。他眼睛很亮。',
    options: [
      {
        label: '押上全部积蓄',
        risk: 32,
        fx: { wealth: 30, intellect: 8, joy: 8, physique: -5 },
        fail: { fx: { wealth: -26, joy: -12, intellect: 6, physique: -4 }, text: '两年后项目停了，散伙饭上没人提钱的事。' },
        text: '第三年你们卖掉了公司。你在签字的时候手抖了一下。',
        flags: ['founder'],
      },
      { label: '投一点点，不辞职', fx: { wealth: -6, intellect: 4, joy: 2 }, text: '亏了，但不多。你保住了工资，也保住了那段友谊。' },
      { label: '婉拒', fx: { joy: -2, intellect: 2 }, flags: ['steady'], text: '两年后你听说他们真的做成了。你为他高兴，也为自己难过了一会儿。' },
    ],
  },
  {
    id: 'overwork-warning',
    kicker: '二十八岁',
    minAge: 26,
    maxAge: 30,
    auto: true,
    weight: 11,
    cond: (s) => s.hasFlag('bigtech') || s.stats.physique < 45,
    text: '隔壁组的同事，三十一岁，加班到凌晨，第二天没有来上班。',
    options: [
      { label: '继续', fx: { joy: -7, physique: -3, intellect: 3 }, flags: ['warned'], text: '你那天准时下了班，并且在楼下买了一份从来没吃过的沙拉。第二天你照旧加班到十一点。' },
    ],
  },
  {
    id: 'blind-date',
    kicker: '二十八岁',
    minAge: 26,
    maxAge: 30,
    weight: 10,
    cond: (s) => !s.hasFlag('married'),
    text: '家里安排了一场相亲，地点是一家灯光很亮、谈话很容易被听见的餐厅。',
    options: [
      { label: '认真了解对方', fx: { charm: 4, joy: 3 }, flags: ['met_partner'], text: '你们聊了三个小时，走的时候互相留了微信。' },
      { label: '全程看手机', fx: { joy: -3, charm: -2 }, text: '你妈当晚打了两个电话过来。' },
      { label: '直接说清楚自己不想结婚', fx: { joy: 4, charm: -4 }, flags: ['solo_minded'], text: '对方反而松了一口气，说她也是被逼来的。你们后来成了很好的朋友。' },
    ],
  },
  {
    id: 'friend-borrow',
    kicker: '二十七岁',
    minAge: 24,
    maxAge: 29,
    weight: 9,
    cond: (s) => s.stats.wealth > 45,
    text: '多年的朋友开口借钱，数目不小，说三个月就还。',
    options: [
      { label: '借', fx: { wealth: -12, charm: 6, joy: 2 }, flags: ['generous'], text: '他一年后才还了一半，但每年都记得给你发消息。' },
      { label: '借一小部分', fx: { wealth: -5, charm: 2 }, text: '你说了个数，他顿了顿，说行。' },
      { label: '不借', fx: { wealth: 3, charm: -6, joy: -3 }, text: '你们后来还见面，但话少了一些。' },
    ],
  },
];
